### ISSUE TITLE
No license on project

### ISSUE THREAD

**Issue by ghost** [Pittan/sushi4watchos-sample#1]
I would like to use a significant portion/create a fork of the code in this project for my own application. However, there is no license for this project, which I understand that by default means there are no rights to redistribute the code. If possible, please add a license. Thanks.

https://choosealicense.com/no-permission/

**Comment by Pittan** [comment]
@futurist2422 
Thank you for being interesting to my project!
You can use my code as a MIT license, though, It's being very outdated(Objective-C lol)

I will add a license to my project later today, thank you for notifying me :)

**Comment by Pittan** [comment]
@futurist2422 
I added a LICENSE file on https://github.com/Pittan/sushi4watchos-sample/commit/db61826a40bbade69712631320c1154b7b3a18f7
